apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: attest-sbom4
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: check-sbom
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - image: "ghcr.io/jimbugwadia/demo-java-tomcat:*"
        key: |-
          -----BEGIN PUBLIC KEY-----
          madhu
          -----END PUBLIC KEY-----     
        attestations:
          - predicateType: https://example.com/CycloneDX/v1
